apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webapp
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: mywebapp-container
        image: my-webapp:latest
        ports:
        - containerPort: 80



